-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 22:44:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bateria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bateria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bateria` (
  `idCarro` INT NOT NULL,
  `Tempo de Carga` VARCHAR(45) NOT NULL,
  `Vida útil` VARCHAR(45) NOT NULL,
  `Capacidade de Bateria` VARCHAR(45) NOT NULL,
  `Capacidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carro` (
  `idCarro` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Preço` FLOAT NULL,
  `Ano` INT NULL,
  `Bateria_idCarro` INT NOT NULL,
  PRIMARY KEY (`idCarro`),
  CONSTRAINT `fk_Carro_Bateria1`
    FOREIGN KEY (`Bateria_idCarro`)
    REFERENCES `mydb`.`Bateria` (`idCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Carro_Bateria1_idx` ON `mydb`.`Carro` (`Bateria_idCarro` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Favorita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Favorita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Favorita` (
  `Pontos de Recarga_idPontos de Recarga` INT NOT NULL,
  `Usuário_idUsuário` INT NOT NULL,
  PRIMARY KEY (`Pontos de Recarga_idPontos de Recarga`, `Usuário_idUsuário`),
  CONSTRAINT `fk_Pontos de Recarga_has_Usuário_Pontos de Recarga1`
    FOREIGN KEY (`Pontos de Recarga_idPontos de Recarga`)
    REFERENCES `mydb`.`Pontos de Recarga` (`idPontos de Recarga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pontos de Recarga_has_Usuário_Usuário1`
    FOREIGN KEY (`Usuário_idUsuário`)
    REFERENCES `mydb`.`Usuário` (`idUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pontos de Recarga_has_Usuário_Usuário1_idx` ON `mydb`.`Favorita` (`Usuário_idUsuário` ASC) VISIBLE;

CREATE INDEX `fk_Pontos de Recarga_has_Usuário_Pontos de Recarga1_idx` ON `mydb`.`Favorita` (`Pontos de Recarga_idPontos de Recarga` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pontos de Recarga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pontos de Recarga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pontos de Recarga` (
  `idPontos de Recarga` INT NOT NULL,
  `Localização` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Tipo de Conector` VARCHAR(45) NOT NULL,
  `Potência` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPontos de Recarga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Possui`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Possui` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Possui` (
  `Usuário_idUsuário` INT NOT NULL,
  `Carro_idCarro` INT NOT NULL,
  PRIMARY KEY (`Usuário_idUsuário`, `Carro_idCarro`),
  CONSTRAINT `fk_Usuário_has_Carro_Usuário`
    FOREIGN KEY (`Usuário_idUsuário`)
    REFERENCES `mydb`.`Usuário` (`idUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_has_Carro_Carro1`
    FOREIGN KEY (`Carro_idCarro`)
    REFERENCES `mydb`.`Carro` (`idCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuário_has_Carro_Carro1_idx` ON `mydb`.`Possui` (`Carro_idCarro` ASC) VISIBLE;

CREATE INDEX `fk_Usuário_has_Carro_Usuário_idx` ON `mydb`.`Possui` (`Usuário_idUsuário` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `idUsuário` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utiliza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utiliza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utiliza` (
  `Carro_idCarro` INT NOT NULL,
  `Pontos de Recarga_idPontos de Recarga` INT NOT NULL,
  PRIMARY KEY (`Carro_idCarro`, `Pontos de Recarga_idPontos de Recarga`),
  CONSTRAINT `fk_Carro_has_Pontos de Recarga_Carro1`
    FOREIGN KEY (`Carro_idCarro`)
    REFERENCES `mydb`.`Carro` (`idCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carro_has_Pontos de Recarga_Pontos de Recarga1`
    FOREIGN KEY (`Pontos de Recarga_idPontos de Recarga`)
    REFERENCES `mydb`.`Pontos de Recarga` (`idPontos de Recarga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Carro_has_Pontos de Recarga_Pontos de Recarga1_idx` ON `mydb`.`Utiliza` (`Pontos de Recarga_idPontos de Recarga` ASC) VISIBLE;

CREATE INDEX `fk_Carro_has_Pontos de Recarga_Carro1_idx` ON `mydb`.`Utiliza` (`Carro_idCarro` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
